export interface Post {
  id: string;
  title: string;
  body: string;
  date: string;
  likes: number;
  comments: number;
  type: "photo" | "video" | "text" | "audio";
  isExclusive: boolean;
  audioSrc?: string;
}

const posts: Record<string, Post[]> = {
  spikeysteve: [
    {
      id: "ss-1",
      title: "Just counted all my spikes: 5,012",
      body: "New personal best. Last month was 4,987 but I've been eating a lot of protein (beetles). Growth mindset.",
      date: "2026-05-13",
      likes: 2841,
      comments: 312,
      type: "text",
      isExclusive: false,
    },
    {
      id: "ss-2",
      title: "Morning stretch routine — full quill extension",
      body: "Every spike, fully extended. The neighbors watched through the fence again. They're fans, they just don't know it yet.",
      date: "2026-05-10",
      likes: 4102,
      comments: 587,
      type: "video",
      isExclusive: true,
    },
    {
      id: "ss-3",
      title: "Post-rain paw close-up",
      body: "Fresh from the lawn. The mud between the toes? Chef's kiss. This is what peak performance looks like.",
      date: "2026-05-06",
      likes: 5230,
      comments: 891,
      type: "photo",
      isExclusive: true,
    },
    {
      id: "ss-4",
      title: "Rate my spike formation",
      body: "Going for the 'alarmed pinecone' look today. Left side is giving more volume than right. Thoughts?",
      date: "2026-04-28",
      likes: 3617,
      comments: 1204,
      type: "photo",
      isExclusive: true,
    },
    {
      id: "ss-5",
      title: "Day in my life: professional spike model",
      body: "5am: wake up. 5:01am: eat beetle. 5:02am: back to sleep. 9pm: real day starts. Forage. Pose. Repeat.",
      date: "2026-04-20",
      likes: 6891,
      comments: 743,
      type: "video",
      isExclusive: true,
    },
  ],

  "mrs-bristles": [
    {
      id: "mb-1",
      title: "Found the BIGGEST slug tonight",
      body: "Absolutely massive. Length of my entire snout. No filter needed. This is raw, unedited foraging content.",
      date: "2026-05-14",
      likes: 8923,
      comments: 1567,
      type: "photo",
      isExclusive: true,
    },
    {
      id: "mb-2",
      title: "3am garden tour — the snails never see me coming",
      body: "Shh. Follow me. Past the begonias, through the gap in the fence, under the watering can... jackpot.",
      date: "2026-05-09",
      likes: 12401,
      comments: 2103,
      type: "video",
      isExclusive: true,
    },
    {
      id: "mb-3",
      title: "Tonight's foraging haul",
      body: "3 slugs, 7 beetles, 1 mysterious berry (did not eat), and a crisp someone dropped. Not my best night, not my worst.",
      date: "2026-05-04",
      likes: 6712,
      comments: 934,
      type: "photo",
      isExclusive: false,
    },
    {
      id: "mb-4",
      title: "ASMR: munching on a beetle",
      body: "Headphones recommended. 12 minutes of pure, uninterrupted crunching. My most requested content.",
      date: "2026-04-25",
      likes: 15230,
      comments: 3891,
      type: "audio",
      isExclusive: true,
      audioSrc: "/audio/mrs-bristles-beetle-asmr.mp3",
    },
    {
      id: "mb-5",
      title: "My secret mushroom spot revealed",
      body: "I've never shown anyone this before. Behind the shed, left of the drainpipe, under the broken pot. You're welcome.",
      date: "2026-04-15",
      likes: 9847,
      comments: 2456,
      type: "photo",
      isExclusive: true,
    },
  ],

  pawsitivelyprickly: [
    {
      id: "pp-1",
      title: "Rating my own toe beans out of 10",
      body: "Front left: 9/10, excellent roundness. Front right: 8/10, slight flattening. Back left: 10/10, perfection. Back right: 7/10, needs moisturiser.",
      date: "2026-05-12",
      likes: 7234,
      comments: 1893,
      type: "text",
      isExclusive: false,
    },
    {
      id: "pp-2",
      title: "Fresh paw prints from today's garden visit",
      body: "Walked through wet cement near the shed. The humans were upset but honestly? Art. These prints are gallery-worthy.",
      date: "2026-05-07",
      likes: 4561,
      comments: 678,
      type: "photo",
      isExclusive: true,
    },
    {
      id: "pp-3",
      title: "Ultimate curl-up tutorial: 47 seconds flat",
      body: "Step 1: tuck nose. Step 2: roll forward. Step 3: tighten. Step 4: become sphere. Don't skip tuck day.",
      date: "2026-05-01",
      likes: 8903,
      comments: 2341,
      type: "video",
      isExclusive: true,
    },
    {
      id: "pp-4",
      title: "Paw spa day — moisturising the beans",
      body: "Using a tiny amount of coconut oil (found near the recycling bin). My paws have never been softer. Subscribers get the full routine.",
      date: "2026-04-22",
      likes: 5672,
      comments: 1102,
      type: "photo",
      isExclusive: true,
    },
    {
      id: "pp-5",
      title: "Soft belly reveal (don't tell anyone)",
      body: "This is my most vulnerable content. The belly. The soft underside. Guard it with your life. I'm trusting you.",
      date: "2026-04-10",
      likes: 11234,
      comments: 4567,
      type: "photo",
      isExclusive: true,
    },
  ],

  "sir-snufflesworth": [
    {
      id: "sn-1",
      title: "Got caught napping in a wellington boot. Again.",
      body: "In my defence, it was warm, dry, and smelled faintly of socks. A gentlehog cannot resist.",
      date: "2026-05-11",
      likes: 14320,
      comments: 3210,
      type: "photo",
      isExclusive: false,
    },
    {
      id: "sn-2",
      title: "Distinguished evening constitutional",
      body: "Through the begonias, past the bird bath, a brief pause at the compost. One does not rush these things.",
      date: "2026-05-05",
      likes: 8721,
      comments: 1654,
      type: "video",
      isExclusive: true,
    },
    {
      id: "sn-3",
      title: "ASMR: 45 minutes of refined snuffling",
      body: "Recorded on a quiet Tuesday evening. Just me, the garden, and my nose. Reviewed as 'distinguished' by 3 separate listeners.",
      date: "2026-04-27",
      likes: 19456,
      comments: 5678,
      type: "audio",
      isExclusive: true,
      audioSrc: "/audio/sir-snufflesworth-snuffling-asmr.mp3",
    },
    {
      id: "sn-4",
      title: "Tea time in the potting shed",
      body: "Found a thimble. It's my cup now. Filled it with rainwater. Sat on a terracotta pot. This is as civilised as it gets.",
      date: "2026-04-18",
      likes: 10234,
      comments: 2891,
      type: "photo",
      isExclusive: true,
    },
    {
      id: "sn-5",
      title: "My monocle fell off mid-snuffle",
      body: "I don't actually own a monocle. But if I did, it would have fallen off. The snuffle was that vigorous. Dignity: compromised.",
      date: "2026-04-08",
      likes: 7612,
      comments: 1987,
      type: "text",
      isExclusive: true,
    },
  ],

  "wheel-queen-winnie": [
    {
      id: "ww-1",
      title: "New PB: 3.7 miles on the wheel",
      body: "My little legs were a BLUR. I could feel the wind in my spikes. The humans woke up. Worth it.",
      date: "2026-05-13",
      likes: 22341,
      comments: 4567,
      type: "text",
      isExclusive: false,
    },
    {
      id: "ww-2",
      title: "Wheel technique breakdown for beginners",
      body: "Lesson 1: approach the wheel. Lesson 2: get on. Lesson 3: run. Lesson 4: never stop. There is no lesson 5.",
      date: "2026-05-08",
      likes: 15678,
      comments: 3456,
      type: "video",
      isExclusive: true,
    },
    {
      id: "ww-3",
      title: "Late-night wheel session — neighbors can hear me",
      body: "2:47am. Full speed. The wheel squeaks. The cage rattles. The humans groan. I am unstoppable.",
      date: "2026-05-02",
      likes: 18934,
      comments: 5123,
      type: "video",
      isExclusive: true,
    },
    {
      id: "ww-4",
      title: "Post-wheel protein meal prep (mealworms)",
      body: "Recovery is key. 12 mealworms, arranged by size. The large ones are for power, the small ones are for speed. Science.",
      date: "2026-04-23",
      likes: 9876,
      comments: 2341,
      type: "photo",
      isExclusive: true,
    },
    {
      id: "ww-5",
      title: "My wheel squeaks and I will NOT oil it",
      body: "The squeak is part of the experience. It's my entrance music. When the humans hear it at 3am, they know: she rides.",
      date: "2026-04-12",
      likes: 13456,
      comments: 4321,
      type: "audio",
      isExclusive: true,
      audioSrc: "/audio/wheel-queen-winnie-squeaky-wheel.mp3",
    },
  ],

  "muddy-morty": [
    {
      id: "mm-1",
      title: "Mud bath tier list: flower bed is S-tier",
      body: "S: flower bed mud. A: compost heap mud. B: puddle mud. C: construction site mud (too gritty). D: bath water (an insult).",
      date: "2026-05-12",
      likes: 6543,
      comments: 1876,
      type: "text",
      isExclusive: false,
    },
    {
      id: "mm-2",
      title: "Absolute STATE of me after the sprinkler",
      body: "The garden sprinkler turned on without warning. I am now 40% mud by volume. This is the content you subscribe for.",
      date: "2026-05-07",
      likes: 11234,
      comments: 3456,
      type: "photo",
      isExclusive: true,
    },
    {
      id: "mm-3",
      title: "Before and after spa day (it's all mud)",
      body: "Before: slightly muddy. After: extremely muddy. The spa is a puddle. The treatment is rolling. I accept no criticism.",
      date: "2026-05-01",
      likes: 8765,
      comments: 2134,
      type: "photo",
      isExclusive: true,
    },
    {
      id: "mm-4",
      title: "Found a puddle. Stayed for 3 hours.",
      body: "They tried to move me. I curled up. They gave up. I returned to the puddle. This is how boundaries work.",
      date: "2026-04-21",
      likes: 14567,
      comments: 4532,
      type: "video",
      isExclusive: true,
    },
    {
      id: "mm-5",
      title: "My humans tried to give me a CLEAN bath",
      body: "Warm water. Soap. A tiny towel. The audacity. The disrespect. I immediately went outside and found mud. Order restored.",
      date: "2026-04-11",
      likes: 16789,
      comments: 5678,
      type: "text",
      isExclusive: true,
    },
  ],

  "quillian-quickfoot": [
    {
      id: "qq-1",
      title: "My quills are looking EXTRA pointy today",
      body: "Must be the weather. Or the attitude. Either way: do not touch. Admire from a safe distance.",
      date: "2026-05-11",
      likes: 5432,
      comments: 987,
      type: "photo",
      isExclusive: false,
    },
    {
      id: "qq-2",
      title: "Speed-foraging challenge: 12 beetles in 4 minutes",
      body: "New record. My technique: rapid snout movements, zero hesitation, eat first ask questions never. The beetles didn't stand a chance.",
      date: "2026-05-06",
      likes: 9876,
      comments: 2345,
      type: "video",
      isExclusive: true,
    },
    {
      id: "qq-3",
      title: "Found a grape bigger than my head",
      body: "Life is good. It rolled away three times before I cornered it near the fence. Then I sat on it. Then I ate it. Victory.",
      date: "2026-04-29",
      likes: 12345,
      comments: 3456,
      type: "photo",
      isExclusive: true,
    },
    {
      id: "qq-4",
      title: "Parkour through the compost bin",
      body: "Over the potato peels, through the eggshells, launched off a banana skin. Stuck the landing on a cabbage leaf. 10/10.",
      date: "2026-04-19",
      likes: 7654,
      comments: 1876,
      type: "video",
      isExclusive: true,
    },
    {
      id: "qq-5",
      title: "Quill care routine — maximum pointiness",
      body: "Step 1: be born with good quills. Step 2: don't wash them too much. Step 3: huff aggressively to make them stand up. That's it. That's the routine.",
      date: "2026-04-09",
      likes: 6543,
      comments: 1234,
      type: "video",
      isExclusive: true,
    },
  ],

  "loafy-lucinda": [
    {
      id: "ll-1",
      title: "Day 47 of sleeping 18 hours. Still not enough.",
      body: "Woke up briefly. Saw the sun. Disapproved. Returned to sleep. Will try again tomorrow. Or the day after.",
      date: "2026-05-14",
      likes: 4321,
      comments: 876,
      type: "text",
      isExclusive: false,
    },
    {
      id: "ll-2",
      title: "The perfect loaf shape: 3 years of practice",
      body: "Round. Compact. Not a single spike out of place. My humans thought I was a bread roll. Highest compliment of my career.",
      date: "2026-05-08",
      likes: 8765,
      comments: 2345,
      type: "photo",
      isExclusive: true,
    },
    {
      id: "ll-3",
      title: "Napping spots ranked: sock drawer is elite",
      body: "S: sock drawer. A: behind the sofa cushion. B: inside a slipper. C: the actual bed they bought me (insultingly obvious).",
      date: "2026-05-02",
      likes: 6543,
      comments: 1987,
      type: "text",
      isExclusive: true,
    },
    {
      id: "ll-4",
      title: "Caught mid-yawn. This is art.",
      body: "Mouth: fully open. Eyes: barely open. Spikes: relaxed. One single tooth visible. Frame this. Put it in the Tate.",
      date: "2026-04-22",
      likes: 11234,
      comments: 3456,
      type: "photo",
      isExclusive: true,
    },
    {
      id: "ll-5",
      title: "10-hour sleep stream highlights",
      body: "0:00 — fell asleep. 3:24 — twitched. 6:15 — rolled slightly. 9:58 — snored once. 10:00 — still asleep. You're welcome.",
      date: "2026-04-12",
      likes: 5432,
      comments: 1234,
      type: "video",
      isExclusive: true,
    },
  ],
};

export function getPostsForHog(username: string): Post[] {
  return posts[username] ?? [];
}
